from dotenv import load_dotenv
import os

load_dotenv()

SUPABASE_URL = os.getenv('SUPABASE_URL')
SUPABASE_SERVICE_ROLE_KEY = os.getenv('SUPABASE_SERVICE_ROLE_KEY')
SUPABASE_TABLE = os.getenv('SUPABASE_TABLE')
SUPABASE_EMAIL_FIELD = os.getenv('SUPABASE_EMAIL_FIELD')
SUPABASE_PHONE_FIELD = os.getenv('SUPABASE_PHONE_FIELD')
SUPABASE_TOKEN_FIELD = os.getenv('SUPABASE_TOKEN_FIELD')
UAZAPI_CONNECT_URL = os.getenv('UAZAPI_CONNECT_URL')